# Site settings
author: Elizabeth Cobb
title: Flatiron Blog
header-img: img/home-bg.png
email: cobbeec@gmail.com
copyright_name: Elizabeth Cobb
description: > # this means to ignore newlines until "baseurl:"
  Reflections on learning to code 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Cobbeec

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
